
os: windows
language: csharp

mono: none
#dotnet: 2.0.0

script: 
  - dotnet restore ./ListFilesBySize.sln
  - dotnet msbuild ./ListFilesBySize.sln
  - dotnet nuget push ./ListFiles/bin/Debug/ListFiles.1.0.0.nupkg -k $nugetApiKey -s $PkiPrivateFeed
  
# artifacts:
#  - path: .\ListFiles\bin\**\*.nupkg
#    name: NuGet
#  
#deploy:
#  - provider: script
#    script: deploy.sh
#    on:
#        branch: master
