
os: windows
language: csharp

mono: none
#dotnet: 2.0.0

script: 
  - dotnet restore ./ListFilesBySize.sln
  - dotnet msbuild ./ListFilesBySize.sln
  - echo $TRAVIS_BUILD_DIR
  - powershell Get-ChildItem -Path $TRAVIS_BUILD_DIR/* -Recurse -Force
    #- dotnet nuget push ./ListFiles/bin/Debug/ListFiles.1.0.0.nupkg -k $nugetApiKey -s "https://api.nuget.org/v3/index.json"
  
# artifacts:
#  - path: .\ListFiles\bin\**\*.nupkg
#    name: NuGet
#  
#deploy:
#  - provider: script
#    script: deploy.sh
#    on:
#        branch: master
