version: 1.3.{build}

build:  
  project: ListFilesBySize.sln   

image: Visual Studio 2019

deploy:
  provider: NuGet
  api_key:
    secure: 3kg1xeoaygli694itcatqg3s
  skip_symbols: false
  artifact: /.*\.nupkg/


