version: 1.2.{build}
build:
  verbosity: minimal
  
#skip_branch_with_pr: false

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2019

- echo This is an AppVeyor test by pki
- echo Perkin Elmer inc.
