# Build worker image (VM template)
image: Visual Studio 2019

version: 1.0.{build}
build:
  verbosity: minimal

branches: 
    except: 
    - "1234" #a dummy branch that does not exist 

branches:
    only:
      - /*.*/

  
# skip_branch_with_pr: false

#---------------------------------#
#    environment configuration    #
#---------------------------------#



- echo This is an AppVeyor test by pki
- echo Perkin Elmer inc.
